# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggallahir', models.DateField()),
                ('jeniskelamin', models.CharField(choices=[('P', 'Perempuan'), ('L', 'Laki-laki')], default='P', max_length=1)),
            ],
        ),
    ]
