# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jeniskelamin', models.CharField(choices=[('P', 'Perempuan'), ('L', 'Laki-laki')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrangTuaSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaayah', models.CharField(max_length=100)),
                ('namaibu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pengajar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.Guru')),
            ],
        ),
    ]
